# Generated by Django 3.1 on 2020-08-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sister_auth', '0001_initial'),
        ('sister_tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tenants',
            field=models.ManyToManyField(blank=True, help_text='The tenants this user belongs to.', related_name='user_set', to='sister_tenants.Client', verbose_name='tenants'),
        ),
    ]
