# Generated by Django 3.0.8 on 2020-07-26 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sister_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaddress',
            name='person',
        ),
        migrations.RemoveField(
            model_name='personcontact',
            name='person',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='PersonAddress',
        ),
        migrations.DeleteModel(
            name='PersonContact',
        ),
    ]
