# Generated by Django 3.1 on 2020-08-27 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sister_tenants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='nama_sekolah',
            new_name='name',
        ),
    ]
