# Generated by Django 3.1 on 2020-08-27 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sister_tenants', '0002_auto_20200827_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='paid_until',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='trial',
            field=models.BooleanField(default=True),
        ),
    ]
