# Generated by Django 3.1 on 2020-08-28 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sister_tenants', '0003_auto_20200827_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='created_at',
        ),
    ]
