# Generated by Django 3.1 on 2020-08-28 15:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sister_auth', '0002_user_tenants'),
        ('sister_tenants', '0004_remove_client_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Sekolah',
        ),
    ]
