# Generated by Django 3.0.8 on 2020-08-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sister_personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='blood_type',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='blood_type'),
        ),
        migrations.AddField(
            model_name='person',
            name='income',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Maximum income per month'),
        ),
    ]
