# Generated by Django 3.0.8 on 2020-08-14 18:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sister_pembelajaran', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresensiKelas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('semester', models.IntegerField(choices=[(1, 1), (2, 2)], default=1)),
                ('tanggal', models.DateField(default=django.utils.timezone.now)),
                ('aktifitas', models.IntegerField(choices=[(1, 'Awal Tahun Pelajaran'), (2, 'Hari Sekolah Efektif'), (3, 'Penilaian Harian'), (4, 'Penilaian Tengah Semester'), (5, 'Penilaian Akhir Semester'), (6, 'Ujian Akhir Sekolah'), (7, 'Penerimaan Rapor'), (8, 'Hari Minggu'), (9, 'Hari Libur Umum'), (10, 'Hari Libur Semester'), (11, 'Hari Libur Puasa')], default=2, help_text='Alasan kelas diliburkan, atau catatan lain.')),
                ('deskripsi', models.CharField(blank=True, help_text='Penjelasan aktifitas.', max_length=250, null=True)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presensi', to='sister_pembelajaran.Kelas')),
            ],
            options={
                'verbose_name': 'Presensi Kelas',
                'verbose_name_plural': 'Presensi Kelas',
                'ordering': ['-tanggal'],
                'unique_together': {('kelas', 'tanggal')},
            },
        ),
        migrations.CreateModel(
            name='PresensiSiswa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.CharField(choices=[('H', 'Hadir'), ('S', 'Sakit'), ('I', 'Izin'), ('A', 'Alfa')], default='H', max_length=3)),
                ('presensi_kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presensi_siswa', to='sister_presensi.PresensiKelas')),
                ('siswa_kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presensi', to='sister_pembelajaran.SiswaKelas')),
            ],
            options={
                'verbose_name': 'Presensi Siswa',
                'verbose_name_plural': 'Presensi Siswa',
                'unique_together': {('presensi_kelas', 'siswa_kelas')},
            },
        ),
    ]
