# Generated by Django 3.0.8 on 2020-08-13 13:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import sister.modules.kurikulum.enums
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sister_pembelajaran', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresensiKelas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('semester', models.IntegerField(choices=[(1, 1), (2, 2)], default=1)),
                ('tanggal', models.DateField(default=django.utils.timezone.now)),
                ('aktifitas', models.IntegerField(choices=[(sister.modules.kurikulum.enums.AktifitasPendidikan['AWAL_TAHUN_PELAJARAN'], 'Awal tahun pelajaran'), (sister.modules.kurikulum.enums.AktifitasPendidikan['HARI_SEKOLAH_EFEKTIF'], 'Hari sekolah efektif'), (sister.modules.kurikulum.enums.AktifitasPendidikan['PENILAIAN_HARIAN'], 'Penilaian harian'), (sister.modules.kurikulum.enums.AktifitasPendidikan['PENILAIAN_TENGAH_SEMESTER'], 'Penilaian tengah semester'), (sister.modules.kurikulum.enums.AktifitasPendidikan['PENILAIAN_AKHIR_SEMESTER'], 'Penilaian akhir semester'), (sister.modules.kurikulum.enums.AktifitasPendidikan['UJIAN_AKHIR_SEKOLAH'], 'Ujian akhir sekolah'), (sister.modules.kurikulum.enums.AktifitasPendidikan['PENERIMAAN_RAPOR'], 'Penerimaan rapor'), (sister.modules.kurikulum.enums.AktifitasPendidikan['HARI_MINGGU'], 'Hari minggu'), (sister.modules.kurikulum.enums.AktifitasPendidikan['HARI_LIBUR_UMUM'], 'Hari libur umum'), (sister.modules.kurikulum.enums.AktifitasPendidikan['HARI_LIBUR_SEMESTER'], 'Hari libur semester'), (sister.modules.kurikulum.enums.AktifitasPendidikan['HARI_LIBUR_PUASA'], 'Hari libur puasa')], default=2, help_text='Alasan kelas diliburkan, atau catatan lain.')),
                ('deskripsi', models.CharField(blank=True, help_text='Penjelasan aktifitas.', max_length=250, null=True)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presensi', to='sister_pembelajaran.Kelas')),
            ],
            options={
                'verbose_name': 'Presensi Kelas',
                'verbose_name_plural': 'Presensi Kelas',
                'ordering': ['-tanggal'],
                'unique_together': {('kelas', 'tanggal')},
            },
        ),
        migrations.CreateModel(
            name='PresensiSiswa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.CharField(choices=[('H', 'Hadir'), ('S', 'Sakit'), ('I', 'Izin'), ('A', 'Alfa')], default='H', max_length=3)),
                ('presensi_kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presensi_siswa', to='sister_presensi.PresensiKelas')),
                ('siswa_kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presensi', to='sister_pembelajaran.SiswaKelas')),
            ],
            options={
                'verbose_name': 'Presensi Siswa',
                'verbose_name_plural': 'Presensi Siswa',
                'unique_together': {('presensi_kelas', 'siswa_kelas')},
            },
        ),
    ]
