# Generated by Django 3.0.8 on 2020-08-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sister_presensi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presensikelas',
            name='aktifitas',
            field=models.IntegerField(choices=[(1, 'Awal tahun pelajaran'), (2, 'Hari sekolah efektif'), (3, 'Penilaian harian'), (4, 'Penilaian tengah semester'), (5, 'Penilaian akhir semester'), (6, 'Ujian akhir sekolah'), (7, 'Penerimaan rapor'), (8, 'Hari minggu'), (9, 'Hari libur umum'), (10, 'Hari libur semester'), (11, 'Hari libur puasa')], default=2, help_text='Alasan kelas diliburkan, atau catatan lain.'),
        ),
    ]
