# Generated by Django 3.0.8 on 2020-08-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sister_presensi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presensikelas',
            name='aktifitas',
        ),
        migrations.AddField(
            model_name='presensikelas',
            name='libur',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='presensikelas',
            name='deskripsi',
            field=models.CharField(blank=True, help_text='Keterangan hari diliburkan, misal: Cuti bersama.', max_length=250, null=True),
        ),
    ]
