# Generated by Django 3.0.8 on 2020-08-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sister_presensi', '0002_auto_20200815_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presensisiswa',
            name='status',
            field=models.CharField(choices=[('H', 'Hadir'), ('S', 'Sakit'), ('I', 'Izin'), ('A', 'Alfa'), ('L', 'Libur')], default='H', max_length=3),
        ),
    ]
