# Generated by Django 3.1 on 2020-08-27 21:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sister_kurikulum', '0001_initial'),
        ('sister_pembelajaran', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PenilaianPembelajaran',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('semester', models.IntegerField(choices=[(1, 1), (2, 2)], default=1)),
                ('mata_pelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penilaian_pembelajaran', to='sister_pembelajaran.matapelajarankelas')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penilaian_pembelajaran', to='sister_pembelajaran.siswakelas')),
            ],
            options={
                'verbose_name': 'Penilaian Pembelajaran',
                'verbose_name_plural': 'Penilaian Pembelajaran',
            },
        ),
        migrations.CreateModel(
            name='ItemPenilaian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('jenis_penilaian', models.IntegerField(choices=[(0, 'TUGAS'), (1, 'PH'), (2, 'PTS'), (3, 'PAS')], default=1, verbose_name='Jenis Penilaian')),
                ('nilai', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('kompetensi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_penilaian', to='sister_kurikulum.kompetensidasar')),
                ('penilaian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nilai', to='sister_penilaian.penilaianpembelajaran')),
            ],
            options={
                'verbose_name': 'Item Penilaian',
                'verbose_name_plural': 'Item Penilaian',
                'ordering': ['jenis_penilaian', 'kompetensi__ki', 'kompetensi__kd'],
                'unique_together': {('jenis_penilaian', 'penilaian', 'kompetensi')},
            },
        ),
    ]
