# Generated by Django 3.0.8 on 2020-08-14 18:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sister_pembelajaran', '0001_initial'),
        ('sister_kurikulum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PenilaianPembelajaran',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('semester', models.IntegerField(choices=[(1, 1), (2, 2)], default=1)),
                ('kompetensi_akhir_semester', models.ManyToManyField(related_name='kompetensi_akhir_semester', to='sister_kurikulum.KompetensiDasar')),
                ('kompetensi_harian', models.ManyToManyField(related_name='kompetensi_harian', to='sister_kurikulum.KompetensiDasar')),
                ('kompetensi_tengah_semester', models.ManyToManyField(related_name='kompetensi_tengah_semester', to='sister_kurikulum.KompetensiDasar')),
                ('kompetensi_tugas', models.ManyToManyField(related_name='kompetensi_tugas', to='sister_kurikulum.KompetensiDasar')),
                ('mata_pelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penilaian_pembelajaran', to='sister_pembelajaran.MataPelajaranKelas')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penilaian_pembelajaran', to='sister_pembelajaran.SiswaKelas')),
            ],
            options={
                'verbose_name': 'Penilaian Pembelajaran',
                'verbose_name_plural': 'Penilaian Pembelajaran',
            },
        ),
        migrations.CreateModel(
            name='ItemPenilaianTugas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('nilai', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('kompetensi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tugas', to='sister_kurikulum.KompetensiDasar')),
                ('penilaian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tugas', to='sister_penilaian.PenilaianPembelajaran')),
            ],
            options={
                'verbose_name': 'Penilaian Tugas',
                'verbose_name_plural': 'Penilaian Tugas',
                'unique_together': {('penilaian', 'kompetensi')},
            },
        ),
        migrations.CreateModel(
            name='ItemPenilaianTengahSemester',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('nilai', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('kompetensi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tengah_semester', to='sister_kurikulum.KompetensiDasar')),
                ('penilaian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tengah_semester', to='sister_penilaian.PenilaianPembelajaran')),
            ],
            options={
                'verbose_name': 'Penilaian Tengah Semester',
                'verbose_name_plural': 'Penilaian Tengah Semester',
                'unique_together': {('penilaian', 'kompetensi')},
            },
        ),
        migrations.CreateModel(
            name='ItemPenilaianHarian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('nilai', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('kompetensi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='harian', to='sister_kurikulum.KompetensiDasar')),
                ('penilaian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harian', to='sister_penilaian.PenilaianPembelajaran')),
            ],
            options={
                'verbose_name': 'Penilaian Harian',
                'verbose_name_plural': 'Penilaian Harian',
                'unique_together': {('penilaian', 'kompetensi')},
            },
        ),
        migrations.CreateModel(
            name='ItemPenilaianAkhirSemester',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('nilai', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('kompetensi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='akhir_semester', to='sister_kurikulum.KompetensiDasar')),
                ('penilaian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='akhir_semester', to='sister_penilaian.PenilaianPembelajaran')),
            ],
            options={
                'verbose_name': 'Penilaian Akhir Semester',
                'verbose_name_plural': 'Penilaian Akhir Semester',
                'unique_together': {('penilaian', 'kompetensi')},
            },
        ),
    ]
