# Generated by Django 3.0.8 on 2020-08-02 10:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sister_pembelajaran', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('sister_kurikulum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penilaian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('nilai', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_sister_penilaian.penilaian_set+', to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Penilaian',
                'verbose_name_plural': 'Penilaian',
            },
        ),
        migrations.CreateModel(
            name='PenilaianPembelajaran',
            fields=[
                ('penilaian_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sister_penilaian.Penilaian')),
                ('semester', models.IntegerField(choices=[(1, 1), (2, 2)], default=1)),
                ('mata_pelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penilaian_pembelajaran', to='sister_pembelajaran.MataPelajaranKelas')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penilaian_pembelajaran', to='sister_pembelajaran.SiswaKelas')),
            ],
            options={
                'verbose_name': 'Penilaian Pembelajaran',
                'verbose_name_plural': 'Penilaian Pembelajaran',
            },
            bases=('sister_penilaian.penilaian',),
        ),
        migrations.CreateModel(
            name='PenilaianEkstraKurikuler',
            fields=[
                ('penilaian_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sister_penilaian.Penilaian')),
                ('semester', models.IntegerField(choices=[(1, 1), (2, 2)], default=1)),
                ('ekskul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penilaian_ekskul', to='sister_kurikulum.EkstraKurikuler')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penilaian_ekskul', to='sister_pembelajaran.SiswaKelas')),
            ],
            options={
                'verbose_name': 'Penilaian Ekstra Kurikuler',
                'verbose_name_plural': 'Penilaian Ekstra Kurikuler',
                'unique_together': {('siswa', 'semester', 'ekskul')},
            },
            bases=('sister_penilaian.penilaian',),
        ),
        migrations.CreateModel(
            name='ItemPenilaianTugas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('nilai', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('kompetensi_dasar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tugas', to='sister_kurikulum.KompetensiDasar')),
                ('penilaian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tugas', to='sister_penilaian.PenilaianPembelajaran')),
            ],
            options={
                'verbose_name': 'Penilaian Tugas',
                'verbose_name_plural': 'Penilaian Tugas',
                'unique_together': {('penilaian', 'kompetensi_dasar')},
            },
        ),
        migrations.CreateModel(
            name='ItemPenilaianTengahSemester',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('nilai', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('kompetensi_dasar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tengah_semester', to='sister_kurikulum.KompetensiDasar')),
                ('penilaian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tengah_semester', to='sister_penilaian.PenilaianPembelajaran')),
            ],
            options={
                'verbose_name': 'Penilaian Tengah Semester',
                'verbose_name_plural': 'Penilaian Tengah Semester',
                'unique_together': {('penilaian', 'kompetensi_dasar')},
            },
        ),
        migrations.CreateModel(
            name='ItemPenilaianHarian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('nilai', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('kompetensi_dasar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='harian', to='sister_kurikulum.KompetensiDasar')),
                ('penilaian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harian', to='sister_penilaian.PenilaianPembelajaran')),
            ],
            options={
                'verbose_name': 'Penilaian Harian',
                'verbose_name_plural': 'Penilaian Harian',
                'unique_together': {('penilaian', 'kompetensi_dasar')},
            },
        ),
        migrations.CreateModel(
            name='ItemPenilaianAkhirSemester',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('nilai', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('kompetensi_dasar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='akhir_semester', to='sister_kurikulum.KompetensiDasar')),
                ('penilaian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='akhir_semester', to='sister_penilaian.PenilaianPembelajaran')),
            ],
            options={
                'verbose_name': 'Penilaian Akhir Semester',
                'verbose_name_plural': 'Penilaian Akhir Semester',
                'unique_together': {('penilaian', 'kompetensi_dasar')},
            },
        ),
    ]
