# Generated by Django 3.0.8 on 2020-08-16 18:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sister_kurikulum', '0005_auto_20200814_1917'),
        ('sister_penilaian', '0002_auto_20200816_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='KompetensiPenilaian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('tugas', models.BooleanField(default=False)),
                ('harian', models.BooleanField(default=False)),
                ('tengah_semester', models.BooleanField(default=False)),
                ('akhir_semester', models.BooleanField(default=False)),
                ('kompetensi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penilaian', to='sister_kurikulum.KompetensiDasar', verbose_name='Kompetensi Dasar')),
                ('penilaian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kompetensi', to='sister_kurikulum.KompetensiDasar', verbose_name='Penilaian')),
            ],
            options={
                'verbose_name': 'Kompetensi Penilaian',
                'verbose_name_plural': 'Kompetensi Penilaian',
                'ordering': ['kompetensi__ki', 'kompetensi__kd'],
                'unique_together': {('penilaian', 'kompetensi')},
            },
        ),
    ]
