# Generated by Django 3.0.8 on 2020-08-16 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sister_penilaian', '0003_kompetensipenilaian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kompetensipenilaian',
            name='penilaian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kompetensi', to='sister_penilaian.PenilaianPembelajaran', verbose_name='Penilaian'),
        ),
    ]
