# Generated by Django 3.0.8 on 2020-08-16 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sister_penilaian', '0004_auto_20200816_1855'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itempenilaianharian',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='itempenilaianharian',
            name='kompetensi',
        ),
        migrations.RemoveField(
            model_name='itempenilaianharian',
            name='penilaian',
        ),
        migrations.AlterUniqueTogether(
            name='itempenilaiantengahsemester',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='itempenilaiantengahsemester',
            name='kompetensi',
        ),
        migrations.RemoveField(
            model_name='itempenilaiantengahsemester',
            name='penilaian',
        ),
        migrations.AlterUniqueTogether(
            name='itempenilaiantugas',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='itempenilaiantugas',
            name='kompetensi',
        ),
        migrations.RemoveField(
            model_name='itempenilaiantugas',
            name='penilaian',
        ),
        migrations.RemoveField(
            model_name='penilaianpembelajaran',
            name='kompetensi_akhir_semester',
        ),
        migrations.RemoveField(
            model_name='penilaianpembelajaran',
            name='kompetensi_harian',
        ),
        migrations.RemoveField(
            model_name='penilaianpembelajaran',
            name='kompetensi_tengah_semester',
        ),
        migrations.RemoveField(
            model_name='penilaianpembelajaran',
            name='kompetensi_tugas',
        ),
        migrations.DeleteModel(
            name='ItemPenilaianAkhirSemester',
        ),
        migrations.DeleteModel(
            name='ItemPenilaianHarian',
        ),
        migrations.DeleteModel(
            name='ItemPenilaianTengahSemester',
        ),
        migrations.DeleteModel(
            name='ItemPenilaianTugas',
        ),
    ]
