# Generated by Django 3.0.8 on 2020-08-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sister_penilaian', '0005_auto_20200816_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kompetensipenilaian',
            name='akhir_semester',
            field=models.BooleanField(default=False, verbose_name='PAS'),
        ),
        migrations.AlterField(
            model_name='kompetensipenilaian',
            name='tengah_semester',
            field=models.BooleanField(default=False, verbose_name='PTS'),
        ),
    ]
