# Generated by Django 3.0.8 on 2020-08-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sister_penilaian', '0006_auto_20200816_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kompetensipenilaian',
            name='harian',
            field=models.BooleanField(default=False, verbose_name='PH'),
        ),
        migrations.AlterField(
            model_name='kompetensipenilaian',
            name='tugas',
            field=models.BooleanField(default=False, verbose_name='TGS'),
        ),
    ]
