# Generated by Django 3.0.8 on 2020-08-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sister_penilaian', '0007_auto_20200816_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kompetensipenilaian',
            old_name='akhir_semester',
            new_name='pas',
        ),
        migrations.RenameField(
            model_name='kompetensipenilaian',
            old_name='harian',
            new_name='ph',
        ),
        migrations.RenameField(
            model_name='kompetensipenilaian',
            old_name='tengah_semester',
            new_name='pts',
        ),
        migrations.RenameField(
            model_name='kompetensipenilaian',
            old_name='tugas',
            new_name='tgs',
        ),
        migrations.AddField(
            model_name='kompetensipenilaian',
            name='desc',
            field=models.BooleanField(default=True, help_text='Gunakan kompetensi dalam deskripsi penilaian akhir', verbose_name='Deskripsi'),
        ),
    ]
