# Generated by Django 3.0.8 on 2020-08-17 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sister_penilaian', '0008_auto_20200817_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kompetensipenilaian',
            name='desc',
        ),
    ]
