# Generated by Django 3.0.8 on 2020-08-17 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sister_penilaian', '0009_remove_kompetensipenilaian_desc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KompetensiPenilaian',
        ),
    ]
