# Generated by Django 3.1 on 2020-10-16 21:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sister_kurikulum', '0001_initial'),
        ('sister_personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EkstraKurikuler',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('nama', models.CharField(max_length=225, verbose_name='nama')),
                ('deskripsi', models.TextField(max_length=225, verbose_name='deskripsi')),
            ],
            options={
                'verbose_name': 'Ekstra Kurikuler',
                'verbose_name_plural': 'Ekstra Kurikuler',
            },
        ),
        migrations.CreateModel(
            name='TahunAngkatan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('tingkat', models.CharField(blank=True, max_length=125, null=True)),
                ('ekskul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='angkatan', to='sister_ekskul.ekstrakurikuler')),
                ('pembina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pembina_ekskul', to='sister_personal.guru')),
                ('tahun_ajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='angkatan', to='sister_kurikulum.tahunajaran')),
            ],
            options={
                'verbose_name': 'Tahun Angkatan',
                'verbose_name_plural': 'Tahun Angkatan',
            },
        ),
        migrations.CreateModel(
            name='PesertaEkstraKurikuler',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('tingkat', models.IntegerField(default=1, editable=False)),
                ('status', models.IntegerField(choices=[(1, 'Aktif'), (2, 'Alumni'), (99, 'Keluar')], default=1)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peserta_ekskul', to='sister_personal.siswa')),
                ('tahun_angkatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peserta_ekskul', to='sister_ekskul.tahunangkatan')),
            ],
            options={
                'verbose_name': 'Peserta Ekskul',
                'verbose_name_plural': 'Peserta Ekskul',
                'unique_together': {('siswa', 'tahun_angkatan')},
            },
        ),
        migrations.CreateModel(
            name='PenilaianEkstraKurikuler',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('semester', models.IntegerField(choices=[(1, 1), (2, 2)], default=1)),
                ('nilai', models.IntegerField(default=60, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(100)])),
                ('predikat', models.CharField(choices=[('A', 'Sangat Baik'), ('B', 'Baik'), ('C', 'Cukup Baik'), ('D', 'Kurang Baik')], max_length=1)),
                ('deskripsi', models.TextField()),
                ('peserta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penilaian_ekskul', to='sister_ekskul.pesertaekstrakurikuler')),
                ('tahun_ajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penilaian_ekskul', to='sister_kurikulum.tahunajaran')),
            ],
            options={
                'verbose_name': 'Penilaian Ekstra Kurikuler',
                'verbose_name_plural': 'Penilaian Ekstra Kurikuler',
                'unique_together': {('peserta', 'tahun_ajaran', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='JadwalEkstraKurikuler',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('semester', models.IntegerField(choices=[(1, 1), (2, 2)], default=1)),
                ('hari', models.IntegerField(choices=[(0, 'Senin'), (1, 'Selasa'), (2, 'Rabu'), (3, 'Kamis'), (4, 'Jumat'), (5, 'Sabtu'), (6, 'Minggu')], default=0)),
                ('jam_mulai', models.TimeField(default=django.utils.timezone.now)),
                ('jam_berakhir', models.TimeField(default=django.utils.timezone.now)),
                ('deskripsi', models.CharField(blank=True, max_length=225, null=True)),
                ('ekstrakurikuler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadwal', to='sister_ekskul.ekstrakurikuler')),
                ('tahun_ajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_ekskul', to='sister_kurikulum.tahunajaran')),
            ],
            options={
                'verbose_name': 'Jadwal Ekstra Kurikuler',
                'verbose_name_plural': 'Jadwal Ekstra Kurikuler',
                'unique_together': {('hari', 'semester', 'tahun_ajaran', 'ekstrakurikuler')},
            },
        ),
    ]
