# Generated by Django 3.0.8 on 2020-07-28 13:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sister_kurikulum', '0001_initial'),
        ('sister_personal', '0001_initial'),
        ('sister_ruang', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('nama_kelas', models.CharField(max_length=225)),
                ('kelas', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=1)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('AKTIF', 'Aktif'), ('SELESAI', 'Selesai')], default='PENDING', max_length=10)),
                ('guru_kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kelas', to='sister_personal.Guru')),
                ('kurikulum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kelas_belajar', to='sister_kurikulum.Kurikulum')),
                ('ruang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ruang', to='sister_ruang.Ruang')),
                ('tahun_ajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sister_kurikulum.TahunAjaran')),
            ],
            options={
                'verbose_name': 'Kelas',
                'verbose_name_plural': 'Kelas',
            },
        ),
        migrations.CreateModel(
            name='NilaiMataPelajaran',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('mata_pelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nilai_siswa', to='sister_kurikulum.MataPelajaran')),
            ],
            options={
                'verbose_name': 'Nilai Mata Pelajaran',
                'verbose_name_plural': 'Nilai Pelajaran',
            },
        ),
        migrations.CreateModel(
            name='NilaiSiswa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('semester', models.IntegerField(choices=[(1, 1), (2, 2)], default=1)),
            ],
            options={
                'verbose_name': 'Nilai Siswa',
                'verbose_name_plural': 'Nilai Siswa',
            },
        ),
        migrations.CreateModel(
            name='PresensiKelas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('tanggal', models.DateField(default=django.utils.timezone.now)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presensi', to='sister_pembelajaran.Kelas')),
            ],
            options={
                'verbose_name': 'Presensi Kelas',
                'verbose_name_plural': 'Presensi Kelas',
                'unique_together': {('kelas', 'tanggal')},
            },
        ),
        migrations.CreateModel(
            name='NilaiMataPelajaranK13',
            fields=[
                ('nilaimatapelajaran_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sister_pembelajaran.NilaiMataPelajaran')),
                ('nilai_pengetahuan', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('deskripsi_pengetahuan', models.TextField()),
                ('nilai_keterampilan', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('deskripsi_keterampilan', models.TextField()),
            ],
            options={
                'verbose_name': 'Nilai Mata Pelajaran K13',
                'verbose_name_plural': 'Nilai Mata Pelajaran K13',
            },
            bases=('sister_pembelajaran.nilaimatapelajaran',),
        ),
        migrations.CreateModel(
            name='NilaiMataPelajaranKTSP',
            fields=[
                ('nilaimatapelajaran_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sister_pembelajaran.NilaiMataPelajaran')),
                ('nilai', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('deskripsi', models.TextField()),
            ],
            options={
                'verbose_name': 'Nilai Mata Pelajaran KTSP',
                'verbose_name_plural': 'Nilai Mata Pelajaran KTSP',
            },
            bases=('sister_pembelajaran.nilaimatapelajaran',),
        ),
        migrations.CreateModel(
            name='SiswaKelas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.IntegerField(choices=[(1, 'Baru'), (2, 'Tinggal Kelas'), (99, 'Lainnya')], default=1)),
                ('status_lain', models.CharField(blank=True, max_length=56, null=True)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siswa', to='sister_pembelajaran.Kelas')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kelas', to='sister_personal.Siswa')),
            ],
            options={
                'verbose_name': 'Siswa Kelas',
                'verbose_name_plural': 'Siswa Kelas',
                'unique_together': {('siswa', 'kelas')},
            },
        ),
        migrations.CreateModel(
            name='PiketKelas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('hari', models.IntegerField(choices=[(0, 'Senin'), (1, 'Selasa'), (2, 'Rabu'), (3, 'Kamis'), (4, 'Jumat'), (5, 'Sabtu'), (6, 'Minggu')], default=1)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piket', to='sister_pembelajaran.Kelas')),
            ],
            options={
                'verbose_name': 'Piket Kelas',
                'verbose_name_plural': 'Piket Kelas',
                'unique_together': {('kelas', 'hari')},
            },
        ),
        migrations.CreateModel(
            name='NilaiSpiritual',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('nilai', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('deskripsi', models.TextField()),
                ('nilai_siswa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nilai_spiritual', to='sister_pembelajaran.NilaiSiswa')),
            ],
            options={
                'verbose_name': 'Nilai Siswa Model KTSP',
                'verbose_name_plural': 'Nilai Siswa Model KTSP',
            },
        ),
        migrations.CreateModel(
            name='NilaiSosial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('nilai', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('deskripsi', models.TextField()),
                ('nilai_siswa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nilai_sosial', to='sister_pembelajaran.NilaiSiswa')),
            ],
            options={
                'verbose_name': 'Nilai Siswa Model KTSP',
                'verbose_name_plural': 'Nilai Siswa Model KTSP',
            },
        ),
        migrations.AddField(
            model_name='nilaisiswa',
            name='siswa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nilai_siswa', to='sister_pembelajaran.SiswaKelas'),
        ),
        migrations.AddField(
            model_name='nilaimatapelajaran',
            name='nilai_siswa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nilai_matapelajaran', to='sister_pembelajaran.NilaiSiswa'),
        ),
        migrations.AddField(
            model_name='nilaimatapelajaran',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_sister_pembelajaran.nilaimatapelajaran_set+', to='contenttypes.ContentType'),
        ),
        migrations.CreateModel(
            name='MataPelajaranKelas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('kkm', models.PositiveIntegerField(default=65, help_text='Kriteria Ketuntasan Minimal', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('tugas', models.PositiveIntegerField(default=10, help_text='Tugas dan Pekerjaan Rumah', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('ph', models.PositiveIntegerField(default=20, help_text='Penilaian Harian', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('pts', models.PositiveIntegerField(default=30, help_text='Penilaian Tengah Semester', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('pas', models.PositiveIntegerField(default=40, help_text='Penilaian Akhir Semester', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mata_pelajaran_kelas', to='sister_personal.Guru')),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mata_pelajaran_kelas', to='sister_pembelajaran.Kelas')),
                ('mata_pelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mata_pelajaran_kelas', to='sister_kurikulum.MataPelajaran')),
            ],
            options={
                'verbose_name': 'Guru Mata Pelajaran',
                'verbose_name_plural': 'Guru Mata Pelajaran',
                'unique_together': {('kelas', 'mata_pelajaran')},
            },
        ),
        migrations.CreateModel(
            name='JadwalKelas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('hari', models.IntegerField(choices=[(0, 'Senin'), (1, 'Selasa'), (2, 'Rabu'), (3, 'Kamis'), (4, 'Jumat'), (5, 'Sabtu'), (6, 'Minggu')], default=1)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_kelas', to='sister_pembelajaran.Kelas')),
            ],
            options={
                'verbose_name': 'Jadwal Kelas',
                'verbose_name_plural': 'Jadwal Kelas',
                'unique_together': {('hari', 'kelas')},
            },
        ),
        migrations.CreateModel(
            name='ItemJadwalPelajaran',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('jam_mulai', models.TimeField(default=django.utils.timezone.now)),
                ('jam_berakhir', models.TimeField(default=django.utils.timezone.now)),
                ('deskripsi', models.CharField(blank=True, max_length=225, null=True)),
                ('jadwal_kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mata_pelajaran', to='sister_pembelajaran.JadwalKelas')),
                ('mata_pelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadwal', to='sister_pembelajaran.MataPelajaranKelas')),
            ],
            options={
                'verbose_name': 'Jadwal Pelajaran',
                'verbose_name_plural': 'Jadwal Pelajaran',
            },
        ),
        migrations.CreateModel(
            name='ItemJadwalEkstraKurikuler',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('jam_mulai', models.TimeField(default=django.utils.timezone.now)),
                ('jam_berakhir', models.TimeField(default=django.utils.timezone.now)),
                ('deskripsi', models.CharField(blank=True, max_length=225, null=True)),
                ('ekstra_kurikuler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadwal', to='sister_kurikulum.EkstraKurikuler')),
                ('jadwal_kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ekskul', to='sister_pembelajaran.JadwalKelas')),
            ],
            options={
                'verbose_name': 'Jadwal Ekstra Kurikuler',
                'verbose_name_plural': 'Jadwal Ekstra Kurikuler',
            },
        ),
        migrations.CreateModel(
            name='RentangNilai',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('nilai_minimum', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('nilai_maximum', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('predikat', models.CharField(choices=[('A', 'sangat baik'), ('B', 'baik'), ('C', 'cukup baik'), ('D', 'kurang baik'), ('E', 'sangat kurang')], default='A', max_length=1)),
                ('aksi', models.CharField(choices=[('pertahankan', 'pertahankan'), ('tingkatkan', 'tingkatkan'), ('perlu_bimbingan', 'perlu bimbingan')], default='tingkatkan', max_length=125)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentang_nilai', to='sister_pembelajaran.Kelas')),
            ],
            options={
                'verbose_name': 'Rentang Nilai',
                'verbose_name_plural': 'Rentang Nilai',
                'unique_together': {('kelas', 'predikat')},
            },
        ),
        migrations.CreateModel(
            name='PresensiSiswa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.CharField(choices=[('H', 'Hadir'), ('S', 'Sakit'), ('I', 'Izin'), ('A', 'Tanpa Keterangan')], default='H', max_length=3)),
                ('presensi_kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presensi_siswa', to='sister_pembelajaran.PresensiKelas')),
                ('siswa_kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presensi', to='sister_pembelajaran.SiswaKelas')),
            ],
            options={
                'verbose_name': 'Presensi Siswa',
                'verbose_name_plural': 'Presensi Siswa',
                'unique_together': {('presensi_kelas', 'siswa_kelas')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='nilaisiswa',
            unique_together={('siswa', 'semester')},
        ),
        migrations.CreateModel(
            name='ItemPiketKelas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('piket_kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siswa_piket', to='sister_pembelajaran.PiketKelas')),
                ('siswa_kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piket_kelas', to='sister_pembelajaran.SiswaKelas')),
            ],
            options={
                'verbose_name': 'Item PiketKelas',
                'verbose_name_plural': 'Item PiketKelas',
                'unique_together': {('piket_kelas', 'siswa_kelas')},
            },
        ),
    ]
