# Generated by Django 3.0.8 on 2020-08-02 10:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sister_pembelajaran', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nilaisiswa',
            name='berat_badan',
            field=models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='nilaisiswa',
            name='tinggi_badan',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(200)]),
        ),
    ]
