# Generated by Django 3.0.8 on 2020-07-28 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sister_pembelajaran', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nilaimatapelajaran',
            name='nilai_siswa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nilai_mata_pelajaran', to='sister_pembelajaran.NilaiSiswa'),
        ),
    ]
