# Generated by Django 3.0.8 on 2020-07-30 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sister_pembelajaran', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemjadwalpelajaran',
            unique_together={('jadwal_kelas', 'mata_pelajaran')},
        ),
    ]
