# Generated by Django 3.0.8 on 2020-07-30 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sister_pembelajaran', '0002_auto_20200730_0902'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemjadwalpelajaran',
            unique_together=set(),
        ),
    ]
