# Generated by Django 3.0.8 on 2020-08-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sister_pembelajaran', '0002_auto_20200802_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='jadwalekstrakurikuler',
            name='semester',
            field=models.IntegerField(choices=[(1, 1), (2, 2)], default=1),
        ),
        migrations.AddField(
            model_name='jadwalpelajaran',
            name='semester',
            field=models.IntegerField(choices=[(1, 1), (2, 2)], default=1),
        ),
        migrations.AddField(
            model_name='jadwalpiketsiswa',
            name='semester',
            field=models.IntegerField(choices=[(1, 1), (2, 2)], default=1),
        ),
    ]
