# Generated by Django 3.0.8 on 2020-08-14 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sister_kurikulum', '0004_auto_20200814_1853'),
        ('sister_pembelajaran', '0002_matapelajarankelas_kurikulum_mapel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matapelajarankelas',
            name='kurikulum_mapel',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='mata_pelajaran_kelas', to='sister_kurikulum.KurikulumMataPelajaran'),
        ),
    ]
