# Generated by Django 3.0.8 on 2020-07-31 12:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sister_pembelajaran', '0003_auto_20200730_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='nilaimatapelajaran',
            name='no_urut',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='siswakelas',
            name='no_urut',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterUniqueTogether(
            name='itemjadwalpelajaran',
            unique_together={('jadwal_kelas', 'mata_pelajaran')},
        ),
    ]
