# Generated by Django 3.0.8 on 2020-08-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sister_pembelajaran', '0003_auto_20200814_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwalpelajaran',
            name='hari',
            field=models.IntegerField(choices=[(0, 'Senin'), (1, 'Selasa'), (2, 'Rabu'), (3, 'Kamis'), (4, 'Jumat'), (5, 'Sabtu'), (6, 'Minggu')], default=0),
        ),
        migrations.AlterField(
            model_name='jadwalpiketsiswa',
            name='hari',
            field=models.IntegerField(choices=[(0, 'Senin'), (1, 'Selasa'), (2, 'Rabu'), (3, 'Kamis'), (4, 'Jumat'), (5, 'Sabtu'), (6, 'Minggu')], default=0),
        ),
    ]
