# Generated by Django 3.0.8 on 2020-08-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sister_pembelajaran', '0003_auto_20200802_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='kelas',
            name='semester',
            field=models.IntegerField(choices=[(1, 1), (2, 2)], default=1, help_text='Tampilkan informasi kelas berdasarkan semester'),
        ),
        migrations.AlterField(
            model_name='kelas',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('AKTIF', 'Aktif'), ('SELESAI', 'Selesai')], default='PENDING', help_text='Tandai kelas sebagai: Pending, Aktif atau Selesai', max_length=10),
        ),
    ]
