# Generated by Django 3.0.8 on 2020-07-28 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sister_pembelajaran', '0003_auto_20200728_0635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nilaisosial',
            options={'verbose_name': 'Nilai Sosial', 'verbose_name_plural': 'Nilai Sosial'},
        ),
        migrations.AlterModelOptions(
            name='nilaispiritual',
            options={'verbose_name': 'Nilai Spiritual', 'verbose_name_plural': 'Nilai Spiritual'},
        ),
    ]
