# Generated by Django 3.0.8 on 2020-08-02 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sister_kurikulum', '0002_matapelajaran_mulok'),
        ('sister_pembelajaran', '0004_auto_20200802_0414'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jadwalekstrakurikuler',
            unique_together={('hari', 'semester', 'kelas', 'ekstra_kurikuler')},
        ),
        migrations.AlterUniqueTogether(
            name='jadwalpelajaran',
            unique_together={('kelas', 'semester', 'hari', 'mata_pelajaran')},
        ),
        migrations.AlterUniqueTogether(
            name='jadwalpiketsiswa',
            unique_together={('kelas', 'semester', 'hari', 'siswa_kelas')},
        ),
    ]
