# Generated by Django 3.0.8 on 2020-07-28 13:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sister_pembelajaran', '0004_auto_20200728_0638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nilaispiritual',
            name='nilai_siswa',
        ),
        migrations.AddField(
            model_name='nilaisiswa',
            name='deskripsi_sosial',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nilaisiswa',
            name='deskripsi_spiritual',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nilaisiswa',
            name='nilai_sosial',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='nilaisiswa',
            name='nilai_spiritual',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='nilaisiswa',
            name='siswa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nilai_siswa', to='sister_pembelajaran.SiswaKelas'),
        ),
        migrations.DeleteModel(
            name='NilaiSosial',
        ),
        migrations.DeleteModel(
            name='NilaiSpiritual',
        ),
    ]
