# Generated by Django 3.0.8 on 2020-08-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sister_pembelajaran', '0004_auto_20200815_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentangnilai',
            name='aksi',
            field=models.CharField(choices=[('pertahankan', 'pertahankan'), ('tingkatkan', 'perlu peningkatan'), ('perlu_bimbingan', 'perlu bimbingan'), ('sangat_perlu_bimbingan', 'sangat perlu bimbingan')], default='tingkatkan', max_length=125),
        ),
    ]
