# Generated by Django 3.0.8 on 2020-07-31 12:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sister_pembelajaran', '0004_auto_20200731_0519'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kelas',
            options={'ordering': ['kelas', 'tahun_ajaran__tahun_mulai'], 'verbose_name': 'Kelas', 'verbose_name_plural': 'Kelas'},
        ),
        migrations.AlterModelOptions(
            name='siswakelas',
            options={'ordering': ['no_urut'], 'verbose_name': 'Siswa Kelas', 'verbose_name_plural': 'Siswa Kelas'},
        ),
        migrations.AddField(
            model_name='nilaimatapelajaran',
            name='kkm',
            field=models.IntegerField(default=65, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='nilaimatapelajarank13',
            name='predikat_keterampilan',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='nilaimatapelajarank13',
            name='predikat_pengetahuan',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='nilaimatapelajaran',
            name='no_urut',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='siswakelas',
            name='no_urut',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
