# Generated by Django 3.0.8 on 2020-08-17 20:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sister_kurikulum', '0006_auto_20200816_1900'),
        ('sister_pembelajaran', '0005_auto_20200817_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='KompetensiPenilaian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('tgs', models.BooleanField(default=False, verbose_name='TGS')),
                ('ph', models.BooleanField(default=False, verbose_name='PH')),
                ('pts', models.BooleanField(default=False, verbose_name='PTS')),
                ('pas', models.BooleanField(default=False, verbose_name='PAS')),
                ('kompetensi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kompetensi_penilaian', to='sister_kurikulum.KompetensiDasar', verbose_name='Kompetensi Dasar')),
                ('mata_pelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kompetensi_penilaian', to='sister_pembelajaran.MataPelajaranKelas', verbose_name='Penilaian')),
            ],
            options={
                'verbose_name': 'Kompetensi Penilaian',
                'verbose_name_plural': 'Kompetensi Penilaian',
                'ordering': ['kompetensi__ki', 'kompetensi__kd'],
                'unique_together': {('mata_pelajaran', 'kompetensi')},
            },
        ),
    ]
