# Generated by Django 3.0.8 on 2020-08-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sister_pembelajaran', '0005_auto_20200802_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='tahunajaran',
            name='bulan_akhir',
            field=models.IntegerField(choices=[(1, 'Januari'), (2, 'Februari'), (3, 'Maret'), (4, 'April'), (5, 'Mei'), (6, 'Juni'), (7, 'Juli'), (8, 'Agustus'), (9, 'September'), (10, 'Oktober'), (11, 'November'), (12, 'Desember')], default=6),
        ),
        migrations.AddField(
            model_name='tahunajaran',
            name='bulan_mulai',
            field=models.IntegerField(choices=[(1, 'Januari'), (2, 'Februari'), (3, 'Maret'), (4, 'April'), (5, 'Mei'), (6, 'Juni'), (7, 'Juli'), (8, 'Agustus'), (9, 'September'), (10, 'Oktober'), (11, 'November'), (12, 'Desember')], default=7),
        ),
    ]
