# Generated by Django 3.0.8 on 2020-07-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sister_pembelajaran', '0005_auto_20200728_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nilaimatapelajarank13',
            name='deskripsi_keterampilan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nilaimatapelajarank13',
            name='deskripsi_pengetahuan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
