# Generated by Django 3.0.8 on 2020-07-31 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sister_pembelajaran', '0006_auto_20200731_0536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nilaimatapelajarank13',
            name='kompetensi_keterampilan',
        ),
        migrations.RemoveField(
            model_name='nilaimatapelajarank13',
            name='kompetensi_pengetahuan',
        ),
        migrations.AddField(
            model_name='nilaisiswa',
            name='predikat_sosial',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='nilaisiswa',
            name='predikat_spirituan',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
