# Generated by Django 3.0.8 on 2020-08-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sister_pembelajaran', '0006_auto_20200802_0501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presensikelas',
            name='keterangan',
        ),
        migrations.RemoveField(
            model_name='presensikelas',
            name='libur',
        ),
        migrations.AddField(
            model_name='presensikelas',
            name='aktifitas',
            field=models.IntegerField(choices=[(1, 'Awal tahun pelajaran'), (2, 'Hari sekolah efektif'), (3, 'Penilaian harian'), (4, 'Penilaian tengah semester'), (5, 'Penilaian akhir semester'), (6, 'Ujian akhir sekolah'), (7, 'Penerimaan rapor'), (8, 'Hari minggu'), (9, 'Hari minggu'), (10, 'Hari libur semester'), (11, 'Hari libur semester')], default=2, help_text='Alasan kelas diliburkan, atau catatan lain.'),
        ),
        migrations.AddField(
            model_name='presensikelas',
            name='deskripsi',
            field=models.CharField(blank=True, help_text='Penjelasan aktifitas.', max_length=250, null=True),
        ),
    ]
