# Generated by Django 3.0.8 on 2020-07-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sister_pembelajaran', '0006_auto_20200728_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='presensikelas',
            name='semester',
            field=models.IntegerField(choices=[(1, 1), (2, 2)], default=1),
        ),
    ]
