# Generated by Django 3.0.8 on 2020-07-31 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sister_pembelajaran', '0007_auto_20200731_0553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nilaisiswa',
            old_name='predikat_spirituan',
            new_name='predikat_spiritual',
        ),
    ]
