# Generated by Django 3.0.8 on 2020-07-28 09:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EkstraKurikuler',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('nama', models.CharField(max_length=225, verbose_name='nama')),
            ],
            options={
                'verbose_name': 'Ekstra Kurikuler',
                'verbose_name_plural': 'Ekstra Kurikuler',
            },
        ),
        migrations.CreateModel(
            name='Kurikulum',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('kode', models.CharField(editable=False, max_length=25, unique=True)),
                ('nama', models.CharField(max_length=225)),
                ('tahun', models.IntegerField(default=0)),
                ('tingkat', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=1)),
                ('kelas', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=1)),
                ('revisi', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Kurikulum',
                'verbose_name_plural': 'Kurikulum',
                'unique_together': {('tahun', 'tingkat', 'kelas', 'revisi')},
            },
        ),
        migrations.CreateModel(
            name='MataPelajaran',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('kode', models.CharField(max_length=25)),
                ('nama', models.CharField(max_length=225)),
            ],
            options={
                'verbose_name': 'Mata Pelajaran',
                'verbose_name_plural': 'Mata Pelajaran',
            },
        ),
        migrations.CreateModel(
            name='TahunAjaran',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('kode', models.CharField(editable=False, max_length=10, unique=True)),
                ('tahun_mulai', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(3000)])),
                ('tahun_akhir', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(3000)])),
            ],
            options={
                'verbose_name': 'Tahun Ajaran',
                'verbose_name_plural': 'Tahun Ajaran',
            },
        ),
        migrations.CreateModel(
            name='MataPelajaranKurikulum',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('kurikulum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sister_kurikulum.Kurikulum')),
                ('mata_pelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sister_kurikulum.MataPelajaran')),
            ],
            options={
                'verbose_name': 'Mata Pelajaran Kurikulum',
                'verbose_name_plural': 'Mata Pelajaran Kurikulum',
            },
        ),
    ]
