# Generated by Django 3.0.8 on 2020-08-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sister_kurikulum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matapelajaran',
            name='mulok',
            field=models.BooleanField(default=False),
        ),
    ]
