# Generated by Django 3.0.8 on 2020-08-14 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sister_kurikulum', '0002_auto_20200814_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kompetensidasar',
            name='kurikulum_mapel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sister_kurikulum.KurikulumMataPelajaran'),
        ),
    ]
