# Generated by Django 3.0.8 on 2020-08-14 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sister_kurikulum', '0003_auto_20200814_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurikulummatapelajaran',
            name='kurikulum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mata_pelajaran', to='sister_kurikulum.Kurikulum'),
        ),
        migrations.AlterField(
            model_name='kurikulummatapelajaran',
            name='mata_pelajaran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kurikulum', to='sister_kurikulum.MataPelajaran'),
        ),
    ]
