# Generated by Django 3.0.8 on 2020-08-14 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sister_kurikulum', '0004_auto_20200814_1853'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='kurikulummatapelajaran',
            unique_together={('kurikulum', 'mata_pelajaran')},
        ),
    ]
